### ISSUE TITLE
Semantic versioning

### ISSUE THREAD

**Issue by twprzybysz** [oliverfoggin/swift-composable-analytics#2]
Hello @oliverfoggin @JackYoustra 

Can you introduce semantic versioning to this repository? It would be helpful, regarding the latest changes - switching the main to the other TCA version caused some trouble.

**Comment by oliverfoggin** [comment]
> Hello @oliverfoggin @JackYoustra 
> 
> 
> 
> Can you introduce semantic versioning to this repository? It would be helpful, regarding the latest changes - switching the main to the other TCA version caused some trouble.

Hey, sorry about that. Yes absolutely will do.

**Comment by oliverfoggin** [comment]
Hey @twprzybysz

Sorry for the delay with this. I have now added a tag for 0.9.0 with what is currently on main.

I will make an update to support TCA 1.0.0 and update the version also.

Thanks
