### ISSUE TITLE
Analytics Client Initialization

### ISSUE THREAD

**Issue by jagreenwood** [oliverfoggin/swift-composable-analytics#4]
It is often the case that analytics clients expose some type of initialization method, normally taking an api key of some sort.

Is it within scope of this project to implement an `initialization` closure on `AnalyticsClient`?

**Comment by oliverfoggin** [comment]
The `AnalyticsClient` is written as a dependency and extensions are free to add any up front initialisation required in the `static var` that creates the dependency. The client itself is not an analytics provider. But just a way that you can pull your own providers into the dependency system.

In one of ours we use that to send initialisation code to the SDK that provides the analytics for us.

Like...

```
import ProviderSDK

extension AnalyticsClient {
  static var someProvider: Self {
    ProviderSDK.instantiateWithSomeValue("passTheValueIn")
    let theSingletonProvider = ProviderSDK.analyticsSingleton    

    return .init {
      sendAnalytics: { analyticsData in
        theSingletonProvider.sendData(analyticsData)
      }
    }
  }
}
```

Or something like that.

**Comment by jagreenwood** [comment]
Ah ok that makes sense. I was thinking mostly from the perspective of maximizing testability, which I still think there is value in that.

**Comment by oliverfoggin** [comment]
If you had an idea of how you would like to approach it then I'd def be up for seeing some more concrete ideas and discussing ways to approach them or merge them into the project. 😄 

Thanks
